-- Flyway migration: Initial schema for Beer, BeerOrder, BeerOrderLine

-- Table: beer
CREATE TABLE IF NOT EXISTS beer (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER,
    beer_name VARCHAR(255) NOT NULL,
    beer_style VARCHAR(255),
    upc VARCHAR(255),
    quantity_on_hand INTEGER,
    price DECIMAL(19,2),
    created_date TIMESTAMP,
    update_date TIMESTAMP
);

-- Table: beer_order
CREATE TABLE IF NOT EXISTS beer_order (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER,
    customer_ref VARCHAR(255),
    payment_amount DECIMAL(19,2),
    status VARCHAR(255),
    created_date TIMESTAMP,
    update_date TIMESTAMP
);

-- Table: beer_order_line
CREATE TABLE IF NOT EXISTS beer_order_line (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER,
    order_quantity INTEGER,
    quantity_allocated INTEGER,
    status VARCHAR(255),
    beer_order_id INTEGER NOT NULL,
    beer_id INTEGER NOT NULL,
    created_date TIMESTAMP,
    update_date TIMESTAMP,
    CONSTRAINT fk_beer_order_line_order FOREIGN KEY (beer_order_id) REFERENCES beer_order(id) ON DELETE CASCADE,
    CONSTRAINT fk_beer_order_line_beer FOREIGN KEY (beer_id) REFERENCES beer(id)
);

CREATE INDEX IF NOT EXISTS idx_beer_order_line_order ON beer_order_line(beer_order_id);
CREATE INDEX IF NOT EXISTS idx_beer_order_line_beer ON beer_order_line(beer_id);
