-- Flyway migration: Add Customer table and update BeerOrder

-- Table: customer
CREATE TABLE IF NOT EXISTS customer (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    phone_number VARCHAR(255),
    address_line_1 VARCHAR(255) NOT NULL,
    address_line_2 VARCHAR(255),
    city VARCHAR(255) NOT NULL,
    state VARCHAR(255) NOT NULL,
    postal_code VARCHAR(255) NOT NULL,
    created_date TIMESTAMP,
    update_date TIMESTAMP
);

-- Update Table: beer_order
ALTER TABLE beer_order ADD COLUMN customer_id INTEGER;

-- Add foreign key constraint
ALTER TABLE beer_order ADD CONSTRAINT fk_beer_order_customer FOREIGN KEY (customer_id) REFERENCES customer(id);

-- Add index
CREATE INDEX IF NOT EXISTS idx_beer_order_customer ON beer_order(customer_id);
